In [10]:
import numpy as np

In [31]:
def conv2d(input, kernel):
    H, W = input.shape
    KH, KW = kernel.shape
    out_H = H - KH + 1
    out_W = W - KW + 1
    output = np.zeros((out_H, out_W))

    for i in range(out_H):
        for j in range(out_W):
            patch = input[i:i+KH, j:j+KW]
            conv_value = np.sum(patch * kernel)
            output[i, j] = conv_value
            print(f"Patch at ({i},{j}):\n{patch}")
            print(f"Convolved value: {conv_value}\n")

    relu_output = np.maximum(output, 0)
    print(f"Final Output after ReLU:\n{relu_output}")
    return relu_output


x = np.arange(25).reshape(5, 5)

k = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

conv2d(x, k)

Patch at (0,0):
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]
Convolved value: -6

Patch at (0,1):
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
Convolved value: -6

Patch at (0,2):
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
Convolved value: -6

Patch at (1,0):
[[ 5  6  7]
 [10 11 12]
 [15 16 17]]
Convolved value: -6

Patch at (1,1):
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]
Convolved value: -6

Patch at (1,2):
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
Convolved value: -6

Patch at (2,0):
[[10 11 12]
 [15 16 17]
 [20 21 22]]
Convolved value: -6

Patch at (2,1):
[[11 12 13]
 [16 17 18]
 [21 22 23]]
Convolved value: -6

Patch at (2,2):
[[12 13 14]
 [17 18 19]
 [22 23 24]]
Convolved value: -6

Final Output after ReLU:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])